module.exports = [
'my unit-tests failed.',
'tried the program, but it was buggy.',
'tomorrow we will do standup.',
'the drive has a 2TB capacity.',
'i need a new power supply.',
'can you play some new music?',
'sure',
'okay',
'sounds good',
'alright',
'why not',
'why not do that',
'why shouldnt we',
'why the hell not',
'yes',
'yes please',
'fine',
'that would be fine',
'i would be fine with that outcome',
'yep',
'yup',
'hell yeah',
'i suppose so',
'surely',
'great lets do that',
'go for it',
'knock yourself out',
'that would be fine and dandy',
'yeah well go with that',
'no thank you',
'please do not',
'please dont',
'dont do that',
'that is not what i want',
'i would rather have something else',
'go back',
'try again',
'nope',
'nuh-uh',
'no',
'dont',
'do not',
'i would rather you not',
'could you do something else',
'this is not what i signed up for',
'please stop that',
'we need to try something else',
'that is not what i asked for',
'i dont think that is what i would prefer',
'just some food',
'some kind of food',
'whatever food you think is best',
'something to eat',
'why do i have to give a list',
'i dont want to',
'i would prefer not to give a list',
'cant you choose my food for me',
'any kind of food',
'whichever kind of food you think best',
'whatever food my friends want',
'what are my options',
'can you give me a list of options',
'what kinds of food are there',
'not sure what you want',
'what can i get',
'just some food please',
'perhaps you could please make a recommendation',
'can you give me a list of options please',
'im just not sure',
'this is a rubbish response',
'its no use its nonsense', 
'can you tell me my options',
'what are my options',
'what are some categories of food',
'can you give me some examples',
'how about an example',
'an example would be good',
'can i get a list of choices',
'how about you list some choices',
'give some options',
'genres',
'genre',
'can you provide an example',
'list',
'lists',
'options',
'categories',
'what are the classes of restaurants i can choose',
'what are the groups',
'what groups can i choose',
'what kind of restaurants',
'what kind of eateries',

'help me',
'i need some help',
'could i get some help please',
'i dont know what to do',
'wont you help me',
'assistance',
'assist me please',
'can i get some assistance',
'what are my options',
'what commands can i execute',
'what are the commands',
'what can i do',
'what do i do next',
'what happens next',
'im not sure what happened',
'can you give me options',
'what are the available commands',
'tell me the commands',
'i require aid',
'succor',
'tell me about yourself',
'tell me about the app',
'whats the story behind this app',
'what do you do',
'what is your purpose',
'what is your name',
'what are you about',
'what is this',
'what is this app about',
'who am i talking to',
'who am i addressing',
'who is this',
'tell me',
'give me some info',
'can i have some general information please',
'i just want to know about the app',
'i want to know about you',
'i want to understand you virgil',
'tell me about virgil',
'who is virgil',
'i would like chinese or korean',
'japanese please',
'something like pizza or burgers would be good',
'korean, or any kind of asian fusion, or some other asian food',
'whatever is tasty',
'something that tastes good',
'afghan african american',
'african arabian burgers',
'american austrain bangladeshi sushi',
'arabian thai indian',
'argentine',
'asian fusion',
'australian american burgers',
'austrian',
'bangladeshi austrian',
'bistro brunch sushi',
'brasseries',
'basque',
'belgian',
'brazilian breakfast brunch sushi',
'brunch',
'breakfast',
'british',
'burger korean chinese',
'buffet',
'burmese buffet',
'cafe',
'cajun',
'creole',
'cambodian',
'canadian',
'carribean',
'cheesesteaks canadian cafe',
'chicken',
'chicken wings',
'chinese korean japanese',
'comfort food',
'creperies',
'crepes bistro',
'cuban',
'czech',
'deli',
'diner',
'ethiopian',
'fast food',
'filipino',
'fondue',
'food stands',
'french',
'gastropub',
'german',
'gluten free',
'greek',
'halal',
'hawaiian',
'himalyan',
'napalese',
'hot pot',
'hungarian',
'iberian',
'indian',
'indonesian',
'international',
'irish italian japanese',
'italian',
'japanese',
'korean',
'kosher gluten free',
'laotian',
'latin',
'malaysian',
'meditteranean',
'mexican',
'middle eastern',
'modern european',
'mongolian',
'moroccan',
'nicaraguan noodles korean chinese japanese',
'noodles',
'pakistani',
'pan asian',
'persian',
'iranian',
'peruvian',
'pizza burgers fast food',
'polish',
'portuguese',
'poutine',
'russian',
'salad',
'sandwich',
'scandinavian',
'scottish indian burgers',
'seafood',
'singaporean',
'slovakian',
'soul food',
'soup thai',
'southern',
'spanish',
'sri lankan',
'steak steakhouse',
'steakhouse',
'sushi',
'syrian thai',
'taiwanese',
'tapas taiwanese chinese korean',
'tex-mex',
'thai',
'turkish',
'ukrainian',
'vegan',
'vegetarian',
'vietnamese',
'waffle vietnamese vegetarian burgers',
'i would rather have waffles but i would be happy with any breakfast food',
'is there any good singaporean food near me',
'slovakian, spanish, or scottish',
'i suppose either pizza or peruvian',
'everyone needs kosher or gluten-free',
'everyone needs kosher or gluten-free'
];
