module.exports = [
"You have entered an invalid username or password",
"The password you entered for the email or username user3 is incorrect. Lost your password?",
"Incorrect password",
"Access denied for user",
"Access denied for user 'admin'@'localhost",
"The password you entered for the email or username user3 is incorrect",
"Incorrect username and password for user",
"The username you provided is incorrect",
"Username or password was incorrect",
"Your password is invalid!",
"Your username is invalid!",
"Incorrect username and password",
"Username incorrect!",
"Email is incorrect",
"Username is incorrect",
"Username or password is incorrect",
"Incorrect username or password",
"Username not found",
"Incorrect username or email",
"ERROR_INCORRECT_USERNAME_OR_EMAIL",
"ERROR_INCORRECT_USERNAME_OR_PASSWORD",
"ERROR_USERNAME_NOT_FOUND",
"Email is incorrect",
"Mobile is incorrect",
"Username is incorrect",
"Email is incorrect",
"Account is locked",
"Password is incorrect",
"Account is incorrect",
"Account not exist",
"Account can not be empty",
"Username or password is incorrect",
"Captcha is incorrect",
"Logged in successful",
"Operation failed",
"Invalid parameters",
"Incorrect access token",
"Invalid access token",
"This user is disabled",
"Your username was incorrect, please try again",
"Your password was incorrect, please try again",
"Incorrect username or password; failed to log in",
"Username is incorrect",
"Incorrect username or password",
"Authentication failed - incorrect username and/or password",
"Authentication failed",
"Incorrect userName",
"Incorrect username",
"Incorrect Password",
"Username is incorrect",
"Username or password is incorrect",
"Permission denied",
"_invalidPassword",
"ERR_PASSWORD_INVALID",
"Invalid username or password",
"The user name or password that you entered was invalid",
"Invalid Username or Password",
"A password is required",
"Validation FAILED.",
"There was an error with your E-Mail/Password combination. Please try again.",
"That Windows Live ID doesnt exist. Enter a different ID or get a new one.",
"That password is incorrect. Try again.",
"username or password is invalid",
"The password you gave is in correct",
"You have entered an invalid username or password",
"The password you entered for the email or username user3 is incorrect. Lost your password?",
"Incorrect password",
"Access denied for user",
"Access denied for user 'admin'@'localhost",
"The password you entered for the email or username user3 is incorrect",
"Incorrect username and password for user",
"The username you provided is incorrect",
"Username or password was incorrect",
"Your password is invalid!",
"Your username is invalid!",
"Incorrect username and password",
"Username incorrect!",
"Email is incorrect",
"Username is incorrect",
"Username or password is incorrect",
"Incorrect username or password",
"Username not found",
"Incorrect username or email",
"ERROR_INCORRECT_USERNAME_OR_EMAIL",
"ERROR_INCORRECT_USERNAME_OR_PASSWORD",
"ERROR_USERNAME_NOT_FOUND" ,
"Email is incorrect",
"Mobile is incorrect" ,
"Username is incorrect" ,
"Email is incorrect",
"Account is locked",
"Password is incorrect",
"Account is incorrect",
"Account not exist",
"Account can not be empty",
"Username or password is incorrect" ,
"Captcha is incorrect",
"Logged in successful",
"Operation failed",
"Invalid parameters" ,
"Incorrect access token",
"Invalid access token",
"This user is disabled",
"Your username was incorrect, please try again",
"Your password was incorrect, please try again",
"Incorrect username or password; failed to log in",
"Username is incorrect",
"Incorrect username or password",
"Authentication failed - incorrect username and/or password",
"Authentication failed",
"Incorrect userName",
"Incorrect username",
"Incorrect Password",
"Username is incorrect",
"Username or password is incorrect",
"Permission denied",
"_invalidPassword",
"ERR_PASSWORD_INVALID",
"Invalid username or password",
"The user name or password that you entered was invalid",
"Invalid Username or Password",
"A password is required",
"Validation FAILED.",
"There was an error with your E-Mail/Password combination. Please try again.",
"That Windows Live ID doesnt exist. Enter a different ID or get a new one.",
"That password is incorrect. Try again.",
"username or password is invalid",
"The password you gave is in correct",
"You have entered an invalid username or password",
"The password you entered for the email or username user3 is incorrect. Lost your password?",
"Incorrect password",
"Access denied for user",
"Access denied for user 'admin'@'localhost",
"The password you entered for the email or username user3 is incorrect",
"Incorrect username and password for user",
"The username you provided is incorrect",
"Username or password was incorrect",
"Your password is invalid!",
"Your username is invalid!",
"Incorrect username and password",
"Username incorrect!",
"Email is incorrect",
"Username is incorrect",
"Username or password is incorrect",
"Incorrect username or password",
"Username not found",
"Incorrect username or email",
"ERROR_INCORRECT_USERNAME_OR_EMAIL",
"ERROR_INCORRECT_USERNAME_OR_PASSWORD",
"ERROR_USERNAME_NOT_FOUND" ,
"Email is incorrect",
"Mobile is incorrect" ,
"Username is incorrect" ,
"Email is incorrect",
"Account is locked",
"Password is incorrect",
"Account is incorrect",
"Account not exist",
"Account can not be empty",
"Username or password is incorrect" ,
"Captcha is incorrect",
"Logged in successful",
"Operation failed",
"Invalid parameters" ,
"Incorrect access token",
"Invalid access token",
"This user is disabled",
"Your username was incorrect, please try again",
"Your password was incorrect, please try again",
"Incorrect username or password; failed to log in",
"Username is incorrect",
"Incorrect username or password",
"Authentication failed - incorrect username and/or password",
"Authentication failed",
"Incorrect userName",
"Incorrect username",
"Incorrect Password",
"Username is incorrect",
"Username or password is incorrect",
"Permission denied",
"_invalidPassword",
"ERR_PASSWORD_INVALID",
"Invalid username or password",
"The user name or password that you entered was invalid",
"Invalid Username or Password",
"A password is required",
"Validation FAILED.",
"There was an error with your E-Mail/Password combination. Please try again.",
"That Windows Live ID doesnt exist. Enter a different ID or get a new one.",
"That password is incorrect. Try again.",
"username or password is invalid",
"The password you gave is in correct",
"You have entered an invalid username or password",
"The password you entered for the email or username user3 is incorrect. Lost your password?",
"Incorrect password",
"Access denied for user",
"Access denied for user 'admin'@'localhost",
"The password you entered for the email or username user3 is incorrect",
"Incorrect username and password for user",
"The username you provided is incorrect",
"Username or password was incorrect",
"Your password is invalid!",
"Your username is invalid!",
"Incorrect username and password",
"Username incorrect!",
"Email is incorrect",
"Username is incorrect",
"Username or password is incorrect",
"Incorrect username or password",
"Username not found",
"Incorrect username or email",
"ERROR_INCORRECT_USERNAME_OR_EMAIL",
"ERROR_INCORRECT_USERNAME_OR_PASSWORD",
"ERROR_USERNAME_NOT_FOUND",
"Email is incorrect",
"Mobile is incorrect",
"Username is incorrect",
"Email is incorrect",
"Account is locked",
"Password is incorrect",
"Account is incorrect",
"Account not exist",
"Account can not be empty",
"Username or password is incorrect" ,
"Captcha is incorrect",
"Logged in successful",
"Operation failed",
"Invalid parameters" ,
"Incorrect access token",
"Invalid access token",
"This user is disabled",
"Your username was incorrect, please try again",
"Your password was incorrect, please try again",
"Incorrect username or password; failed to log in",
"Username is incorrect",
"Incorrect username or password",
"Authentication failed - incorrect username and/or password",
"Authentication failed",
"Incorrect userName",
"Incorrect username",
"Incorrect Password",
"Username is incorrect",
"Username or password is incorrect",
"Permission denied",
"_invalidPassword",
"ERR_PASSWORD_INVALID",
"Invalid username or password",
"The user name or password that you entered was invalid",
"Invalid Username or Password",
"A password is required",
"Validation FAILED.",
"There was an error with your E-Mail/Password combination. Please try again.",
"That Windows Live ID doesnt exist. Enter a different ID or get a new one."
];